imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }
    - { resource: "EXT:bootstrap_package/Configuration/RTE/Default.yaml" }

editor:
    externalPlugins:
        test: 
            resource: "EXT:ku_prototype/Resources/Public/CKEditor/Plugins/test/plugin.js"
        # codemirror:
        #     resource: "EXT:ku_prototype/Resources/Public/CKEditor/Plugins/codemirror/plugin.js"

    config:
        contentsCss: "EXT:bootstrap_package/Resources/Public/Css/bootstrap5-rte.min.css"

        stylesSet:
            - { name: "KU test", element: "div", attributes: { 'class': 'ku-test' } }

        scayt_autoStartup: true

        format_tags: "p;div;h2;h3;h4;h5;pre"


        disallowedContent:
            - "i,s,*{font*},table[cellspacing,cellpadding,border]"

        extraAllowedContent:
            - "iframe(*){*}[*]"

        removeFormatAttributes:
            - "lang,width,height,align,hspace,valign"

        removePlugins:
            - image

        removeButtons:
            - Italic
            - Underline
            - Strike

        extraPlugins:
            - justify
            - autolink
            - test
            # - sourcedialog
            # - codemirror

    processing:
        allowTags:
            - iframe