imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }
    - { resource: "EXT:bootstrap_package/Configuration/RTE/Default.yaml" }

editor:
    externalPlugins:
        ku_prototype_codemirror:
            resource: "EXT:ku_prototype/Resources/Public/CKeditor/Plugins/Codemirror/plugin.min.js"

    config:
        contentsCss: "EXT:bootstrap_package/Resources/Public/Css/bootstrap5-rte.min.css"

        stylesSet:
            - { name: "Test", element: "div", attributes: { 'class': 'ku-test' } }

        scayt_autoStartup: true

        disallowedContent:
            - "i,s,*{font*},table[cellspacing,cellpadding,border]"

        extraAllowedContent:
            - "iframe(*){*}[*]"

        removeFormatAttributes:
            - "lang,width,height,align,hspace,valign"

        removeButtons:
            - Italic

        extraPlugins:
            - ku_prototype_codemirror

        format_tags: "p;div;h2;h3;h4;h5;pre"

    processing:
        allowTags:
            - iframe